### ISSUE TITLE
Word count option greyed out, keybinding unresponsive

### ISSUE THREAD

**Issue by faaizajaz** [lionandoil/SublimeLaTeXWordCount#22]
Didn't touch my sublime installation, the plugin just stopped working. Tried reinstalling the package but the problem persists. The word count option is greyed out, and the keyboard shortcut does not work. No error message or anything.

**Comment by kevinstadler** [comment]
Could be any of the pull requests I just merged - can you give more information on your ST version? Are there any error messages shown under `View > Show Console` when you try using the `Ctrl+Shift+C` shortcut?

**Comment by faaizajaz** [comment]
Ah. Should have checked the console. No error messages when I try to run it, but it seems like the package fails to initialize:

`Reloading plugin C:\Users\Faaiz\AppData\Roaming\Sublime Text 2\Packages\LaTeX Word Count\WordCount.py
Traceback (most recent call last):
  File ".\sublime_plugin.py", line 62, in reload_plugin
  File ".\WordCount.py", line 117, in <module>
    r"([^{}]+)\.(tmLanguage|sublime-syntax)".format(os.sep)).search
ValueError: zero length field name in format`

**Comment by kevinstadler** [comment]
Ah, probably a Windows path separator issue - could you do me a favour and test if the plugin works when you remove `.format(os.sep)` from that line?

**Comment by faaizajaz** [comment]
The plot thickens. Word count works after removing that snippet, with the caveat: "No custom support for Packages/LaTeX/LaTeX syntax, treating file as plain text". 

Syntax in ST is set to LaTeX, code highlighting etc is working fine.

**Comment by kevinstadler** [comment]
I see. I'm gonna revert back to the old syntax detection for now, maybe @mpvharmelen has an idea how his approach from 88c805f could be made to work for Windows too?

**Comment by faaizajaz** [comment]
Thanks.

**Comment by kevinstadler** [comment]
Thank you for the swift reporting!
